<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <IsPackable>true</IsPackable>
        <PackageId>squalor.DataBall</PackageId>
        <Version>1.0.0</Version>
        <Authors>Jon Robbins</Authors>
        <Description>Versatile data handling class for test executive applications, supporting import/export in various formats, data manipulation, metadata, and configuration-based relationships. Supports large datasets via chunked imports and partitioned Parquet exports.</Description>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/squalor-xyz/DataBall</RepositoryUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RootNamespace>Squalor.DataBall</RootNamespace>
        <OutputType>Library</OutputType>
        <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Analysis" Version="0.22.2" />
        <PackageReference Include="Parquet.Net" Version="5.2.0" />
        <PackageReference Include="SharpCompress" Version="0.40.0" />
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
        <PackageReference Include="NLog" Version="5.3.4" />
        <PackageReference Include="xunit" Version="2.5.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
        <PackageReference Include="IronCompress" Version="1.6.3" />
    </ItemGroup>
</Project>