<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Jon Robbins</Authors>
    <RepositoryUrl>https://github.com/squalor-xyz/DataBall</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/squalor-xyz/DataBall</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile Condition="'$(MSBuildProjectName)' == 'DataBall'">true</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
